version: '3.8'
services:
  broker:
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672

  sagas:
    build:
      context: ./app/sagas
    depends_on:
      - broker
    environment:
      AMQP: amqp://broker
    # volumes:
    #   - .:/home/app

  email:
    build:
      context: ./app/email
    depends_on:
      - broker
    environment:
      AMQP: amqp://broker
    # volumes:
    #   - .:/home/app
    # deploy:
    #   replicas: 2

  user:
    build:
      context: ./app/user
    depends_on:
      - broker
    environment:
      AMQP: amqp://broker
    # volumes:
    #   - .:/home/app

  gateway:
    build:
      context: ./app/gateway
    depends_on:
      - broker
    ports:
      - 8080:8080
    environment:
      AMQP: amqp://broker
      GATEWAY_PORT: 8080
    # volumes:
    #   - .:/home/app
